name: Arma 3 Tools
description: Setup Arma 3 Tools
inputs:
  toolsUrl:
    description: URL to hosted ZIP file with Arma 3 Tools
    required: true
runs:
  using: composite
  steps:
    - name: Install Arma 3 Tools
      shell: pwsh
      env:
        ARMA3_TOOLS_URL: ${{ inputs.toolsUrl }}
      run: |
        Invoke-WebRequest "$env:ARMA3_TOOLS_URL" -OutFile arma3tools.zip

        if ($IsWindows) {
          Expand-7ZipArchive -Path arma3tools.zip -DestinationPath C:\arma3tools
          
          regedit /S "${{ github.action_path }}\arma3tools.reg"

          (Get-Content C:\arma3tools\BinMake\binMakeRules.txt) -replace 'O:\\Arma3CommunityTools', 'C:\arma3tools' | Set-Content C:\arma3tools\BinMake\binMakeRules.txt
          choco install directx
        } else {
          Expand-7ZipArchive -Path arma3tools.zip -DestinationPath ~/.local/share/arma3tools

          sudo apt-get install -y wine64
        }

        Remove-Item arma3tools.zip
