name: Arma 3 Tools
description: Setup Arma 3 Tools
inputs:
  toolsUrl:
    description: URL to hosted ZIP file with Arma 3 Tools
    required: true
runs:
  using: 'node20'
  main: 'dist/main/index.js'
