name: Arma 3 Tools
description: Setup Arma 3 Tools
inputs:
  toolsUrl:
    description: URL to hosted ZIP file with Arma 3 Tools
    required: true
runs:
  using: composite
  steps:
    - name: Setup registry values
      run: regedit /S "${{ github.action_path }}\arma3tools.reg"
      shell: pwsh

    - name: Download Arma 3 Tools
      run: |
        Invoke-WebRequest "$env:ARMA3_TOOLS_URL" -OutFile arma3tools.zip
        Expand-Archive -Path arma3tools.zip -DestinationPath C:\arma3tools
        Remove-Item arma3tools.zip
      shell: pwsh
      env:
        ARMA3_TOOLS_URL: ${{ inputs.toolsUrl }}

    - name: Install DirectX
      run: choco install directx
      shell: pwsh
